name: Build Docker images for AHK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build and push Docker images
        working-directory: ./src
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login https://ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
          docker-compose build
          docker-compose push
          docker logout https://ghcr.io
